name: Sync Kaggle Notebooks

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs weekly on Monday at midnight
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install kaggle
      run: pip install kaggle

    - name: Create kaggle.json
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    - name: Download Kaggle notebook
      run: kaggle kernels pull arthur254/logistic-regression-practice -p .

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.em
